cabal-version: 2.2
name: techdraw
version: 0.1.0.0
build-type: Custom

custom-setup
  setup-depends:
    Cabal,
    aeson,
    base,
    bytestring,
    directory,
    filepath,
    megaparsec,

library
  hs-source-dirs:
    src
    generated

  exposed-modules:
    --      KiCad.Types
    --      KiCad.SymbolGenerator
    --      KiCad.Symbol
    --      KiCad.SExprParser
    --      KiCad.Footprint
    --TechDraw.SVG.SVGRender
    -- Electrical
    -- und alle Symbolmodule:
    -- Resistor-Familie
    -- Capacitor-Familie
    -- Induktivitäten / Transformatoren
    -- Schalter
    -- Fuses
    -- Power / Ground
    -- Aktive Bauelemente
    -- Energiequellen
    -- Sonstiges
    -- TechDraw.Electrical.Library
    TechDraw
    TechDraw.Electrical.AllSymbols
    TechDraw.Electrical.BoundingBox
    TechDraw.Electrical.Layout
    TechDraw.Electrical.Ports
    TechDraw.Electrical.Render
    TechDraw.Electrical.Symbols
    TechDraw.Electrical.Symbols.ACSource
    TechDraw.Electrical.Symbols.Battery
    TechDraw.Electrical.Symbols.Capacitor
    TechDraw.Electrical.Symbols.CapacitorPolarized
    TechDraw.Electrical.Symbols.CapacitorTrimmer
    TechDraw.Electrical.Symbols.CapacitorVariable
    TechDraw.Electrical.Symbols.CircuitBreaker
    TechDraw.Electrical.Symbols.Connector
    TechDraw.Electrical.Symbols.DCSource
    TechDraw.Electrical.Symbols.Diode
    TechDraw.Electrical.Symbols.EarthProtective
    TechDraw.Electrical.Symbols.Fuse
    TechDraw.Electrical.Symbols.FuseHolder
    TechDraw.Electrical.Symbols.FuseThermal
    TechDraw.Electrical.Symbols.Ground
    TechDraw.Electrical.Symbols.Inductor
    TechDraw.Electrical.Symbols.LED
    TechDraw.Electrical.Symbols.Lamp
    TechDraw.Electrical.Symbols.Motor
    TechDraw.Electrical.Symbols.OpAmp
    TechDraw.Electrical.Symbols.Potentiometer
    TechDraw.Electrical.Symbols.PushButtonNC
    TechDraw.Electrical.Symbols.PushButtonNO
    TechDraw.Electrical.Symbols.Resistor
    TechDraw.Electrical.Symbols.Switch2P
    TechDraw.Electrical.Symbols.SwitchClosed
    TechDraw.Electrical.Symbols.SwitchDPDT
    TechDraw.Electrical.Symbols.SwitchOpen
    TechDraw.Electrical.Symbols.SwitchSPDT
    TechDraw.Electrical.Symbols.SwitchToggle
    TechDraw.Electrical.Symbols.Terminal
    TechDraw.Electrical.Symbols.ThermistorNTC
    TechDraw.Electrical.Symbols.ThermistorPTC
    TechDraw.Electrical.Symbols.Transformer
    TechDraw.Electrical.Symbols.TransistorNPN
    TechDraw.Electrical.Symbols.TransistorPNP
    TechDraw.Electrical.Symbols.Trimmer
    TechDraw.Electrical.Symbols.Zener
    TechDraw.Electrical.TestAllSymbols
    TechDraw.Electrical.Types
    TechDraw.Electrical.Wire
    TechDraw.Export.PDF
    TechDraw.Export.PNG
    TechDraw.Export.SVG
    TechDraw.Export.Wasm
    TechDraw.Pcb.Core
    TechDraw.Pcb.DSL
    TechDraw.Pcb.Elements.Axes
    TechDraw.Pcb.Elements.Connector
    TechDraw.Pcb.Elements.Dimension
    TechDraw.Pcb.Elements.Label
    TechDraw.Pcb.Elements.ModuleBox
    TechDraw.Pcb.Elements.MountHole
    TechDraw.Pcb.Layout.Align
    TechDraw.Pcb.Layout.Compose
    TechDraw.Pcb.Layout.Grid
    TechDraw.Pcb.Render
    TechDraw.Pcb.Types
    TechDraw.Pcb.Units
    TechDraw.Pcb.Utils
    TechDraw.SVG
    TechDraw.SVG.BoundingBox
    TechDraw.SVG.Center
    TechDraw.SVG.Defaults
    TechDraw.SVG.Matrix
    TechDraw.SVG.Path.Normalize
    TechDraw.SVG.Path.Parser
    TechDraw.SVG.Path.Render
    TechDraw.SVG.Path.Tokenizer
    TechDraw.SVG.Path.Types
    TechDraw.SVG.Paths
    TechDraw.SVG.Primitives
    TechDraw.SVG.Render
    TechDraw.SVG.Style
    TechDraw.SVG.Transform
    TechDraw.SVG.Types
    TechDraw.SVG.Util

  other-modules:
  build-depends:
    --    cairo,
    --    gi-cairo,
    --    gi-gdk3,
    --    gi-gtk,
    --    haskell-gi-base,
    aeson >=2.0,
    base >=4.14 && <5,
    bytestring,
    containers,
    megaparsec >=9.0,
    text,

  default-language: Haskell2010

--executable pcb
--  hs-source-dirs: examples
--  main-is: PCB.hs
--  build-depends:
--  base,
--  techdraw
--  default-language: Haskell2010
--executabel pcb2
--  hs-source-dirs: examples
--  main-is: PCB2.hs
--  build-depends:
--    base,
--    techdraw
--  default-language: Haskell2010
--executable frontpanel
--  hs-source-dirs: examples
--  main-is: FrontPanel.hs
--  build-depends:
--    base,
--      techdraw
--  default-language: Haskell2010
--executable complex-drawing
--  hs-source-dirs: examples
--  main-is: ComplexDrawing.hs
--  build-depends:
--      base,
--      techdraw,
--  default-language: Haskell2010
executable splin-demo
  hs-source-dirs: app
  main-is: Main.hs
  build-depends:
    base,
    techdraw,

  default-language: Haskell2010

--executable electrical-demo
--  hs-source-dirs: examples
--  main-is: ElectricalDemo.hs
--  build-depends:
--    base,
--    techdraw
--  default-language: Haskell2010
--executable generate-symbols
--  main-is: GenerateSymbols.hs
--  hs-source-dirs: app
--  build-depends:
--    base,
--    directory,
--    filepath,
--    megaparsec,
--    techdraw
--  default-language: Haskell2010
executable test-all-symbols
  hs-source-dirs: app
  main-is: TestAll.hs
  build-depends:
    base >=4.14 && <5,
    techdraw,
    text,

  default-language: Haskell2010

--executable zeichnung-demo
--  hs-source-dirs: examples
--  main-is: TestZeichnung.hs
--  build-depends:
-- base,
-- techdraw
-- default-language: Haskell2010
--executable gi-example
--  hs-source-dirs: examples
--  main-is: gi-gtk-cairo.hs
--  build-depends:
--    base,
--    cairo,
--    gi-cairo,
--    gi-gdk3,
--    gi-gtk,
--    haskell-gi-base,
--  default-language: Haskell2010
